switches:
  - ip: "192.168.1.1"
    community: "public"
    name: "Switch-1"
  - ip: "192.168.1.2"
    community: "public"
    name: "Switch-2"
  # سوئیچ‌های دیگر

poll_interval: 3  # ثانیه

vlan_mapping:
  "1-20": 10
  "21-36": 20
  "37-48": 30
